# -*- coding: utf-8 -*-
"""gan_27_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10HLgPY0KuwAdjH5eZCOln6MQlSbDzrM6
"""

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  CELL 0 — Imports & ALL helper functions                               ║
# ║  !! ALWAYS RUN THIS FIRST after any session restart !!                 ║
# ╚══════════════════════════════════════════════════════════════════════════╝

import os, re, math, copy, glob, shutil
from datetime import datetime
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, Model, optimizers, losses

os.environ.setdefault('TF_CPP_MIN_LOG_LEVEL', '2')
print(f"[INFO] TensorFlow {tf.__version__} | "
      f"GPU: {[g.name for g in tf.config.list_physical_devices('GPU')] or 'None (CPU)'}")


# ── Time utilities ────────────────────────────────────────────────────────────

def _t2s(t: str) -> float:
    """HH:MM:SS.ss -> float seconds."""
    h, m, s = t.split(':')
    return int(h) * 3600 + int(m) * 60 + float(s)

def _s2t(t) -> str:
    """float seconds -> HH:MM:SS.ss"""
    if t is None:
        return '00:00:00.00'
    t = float(t)
    h = int(t // 3600);  t -= h * 3600
    m = int(t // 60);    s  = t - m * 60
    return f'{h:02d}:{m:02d}:{s:05.2f}'


# ── Geospatial utilities ──────────────────────────────────────────────────────

_R_NM = 3440.065

def haversine_nm(lat1, lon1, lat2, lon2) -> float:
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1;  dlon = lon2 - lon1
    a = math.sin(dlat/2)**2 + math.cos(lat1)*math.cos(lat2)*math.sin(dlon/2)**2
    return 2 * _R_NM * math.asin(math.sqrt(a))

def find_closest_approach(wpts1: list, wpts2: list):
    best_d, best_i, best_j = float('inf'), 0, 0
    step = max(1, len(wpts1) // 100)
    for i in range(0, len(wpts1), step):
        for j in range(0, len(wpts2), step):
            d = haversine_nm(wpts1[i]['lat'], wpts1[i]['lon'],
                             wpts2[j]['lat'], wpts2[j]['lon'])
            if d < best_d:
                best_d, best_i, best_j = d, i, j
    r = min(step * 2, 40)
    for i in range(max(0, best_i - r), min(len(wpts1), best_i + r)):
        for j in range(max(0, best_j - r), min(len(wpts2), best_j + r)):
            d = haversine_nm(wpts1[i]['lat'], wpts1[i]['lon'],
                             wpts2[j]['lat'], wpts2[j]['lon'])
            if d < best_d:
                best_d, best_i, best_j = d, i, j
    return best_i, best_j, best_d


# ── Data loading & SCN parsing ────────────────────────────────────────────────

def load_csv(csv_path: str) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    required = ['sim_time', 'acid', 'lat', 'lon', 'heading', 'alt', 'ground_speed']
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"CSV missing columns: {missing}")
    print(f"[CSV] Loaded {len(df)} rows | "
          f"sim_time {df.sim_time.min():.0f} - {df.sim_time.max():.0f} s")
    return df

def parse_scn(scn_path: str) -> dict:
    with open(scn_path, 'r') as fh:
        raw_lines = fh.readlines()

    cre_re    = re.compile(
        r'(\d{2}:\d{2}:\d{2}\.\d{2})>\s+CRE\s+(\w+)\s+(\w+)\s+'
        r'([\d.\-]+)\s+([\d.\-]+)\s+([\d.\-]+)\s+([\d.\-]+)\s+([\d.\-]+)',
        re.IGNORECASE)
    addwpt_re = re.compile(
        r'(\d{2}:\d{2}:\d{2}\.\d{2})>\s+ADDWPT\s+\w+\s+([\d.\-]+)\s+([\d.\-]+)',
        re.IGNORECASE)
    alt_re    = re.compile(
        r'(\d{2}:\d{2}:\d{2}\.\d{2})>\s+\w+\s+AT\s+\w+\s+DO\s+ALT\s+\w+\s+([\d.\-]+)',
        re.IGNORECASE)
    spd_re    = re.compile(
        r'(\d{2}:\d{2}:\d{2}\.\d{2})>\s+\w+\s+AT\s+\w+\s+DO\s+SPD\s+\w+\s+([\d.\-]+)',
        re.IGNORECASE)
    del_re    = re.compile(
        r'(\d{2}:\d{2}:\d{2}\.\d{2})>\s+\w+\s+AT\s+\w+\s+DO\s+DEL\s+(\w+)',
        re.IGNORECASE)

    cre_line = None
    wpt_map, alt_map, spd_map = {}, {}, {}
    del_acid = None

    for line in raw_lines:
        line = line.rstrip('\n').strip()
        m = cre_re.match(line)
        if m:
            cre_line = dict(acid=m.group(2), actype=m.group(3),
                            lat=float(m.group(4)), lon=float(m.group(5)),
                            hdg=float(m.group(6)), alt=float(m.group(7)),
                            spd=float(m.group(8)))
            continue
        m = addwpt_re.match(line)
        if m:
            t = _t2s(m.group(1))
            wpt_map[t] = {'lat': float(m.group(2)), 'lon': float(m.group(3)),
                          'time_str': m.group(1)}
            continue
        m = alt_re.match(line)
        if m:
            alt_map[_t2s(m.group(1))] = float(m.group(2))
            continue
        m = spd_re.match(line)
        if m:
            spd_map[_t2s(m.group(1))] = float(m.group(2))
            continue
        m = del_re.match(line)
        if m:
            del_acid = m.group(2).strip()

    prev_alt = cre_line['alt'] if cre_line else 0.0
    prev_spd = cre_line['spd'] if cre_line else 0.0
    waypoints = []
    for idx, t in enumerate(sorted(wpt_map), start=1):
        alt = alt_map.get(t, alt_map.get(t + 1, prev_alt))
        spd = spd_map.get(t, spd_map.get(t + 1, prev_spd))
        waypoints.append(dict(wpt_idx=idx, time_s=t,
                               time_str=wpt_map[t]['time_str'],
                               lat=wpt_map[t]['lat'], lon=wpt_map[t]['lon'],
                               alt=alt, spd=spd))
        prev_alt, prev_spd = alt, spd

    print(f"[SCN] {os.path.basename(scn_path)}: "
          f"{len(waypoints)} waypoints | AC={cre_line['acid'] if cre_line else '?'}")
    return dict(cre=cre_line, waypoints=waypoints, del_acid=del_acid)

def parse_conflict_scn(scn_path: str) -> dict:
    with open(scn_path, 'r') as fh:
        lines = fh.readlines()

    inter_re = re.compile(
        r'#.*Intersection.*lat=([\d.\-]+),\s*lon=([\d.\-]+)', re.IGNORECASE)
    call_re  = re.compile(
        r'(\d{2}:\d{2}:\d{2}\.\d{2})>\s*CALL\s+([\w.\-]+\.scn)', re.IGNORECASE)
    quit_re  = re.compile(
        r'(\d{2}:\d{2}:\d{2}\.\d{2})>QUIT', re.IGNORECASE)

    info = dict(intersection=None,
                ac1_scn=None, ac2_scn=None,
                ac1_call_time=None, ac2_call_time=None,
                quit_time=None)
    call_count = 0

    for line in lines:
        m = inter_re.search(line)
        if m:
            info['intersection'] = (float(m.group(1)), float(m.group(2)))
        m = call_re.search(line)
        if m:
            call_count += 1
            t = _t2s(m.group(1))
            if call_count == 1:
                info['ac1_call_time'] = t
                info['ac1_scn'] = m.group(2)
            else:
                info['ac2_call_time'] = t
                info['ac2_scn'] = m.group(2)
        m = quit_re.search(line)
        if m:
            info['quit_time'] = _t2s(m.group(1))

    print(f"[Conflict SCN] intersection={info['intersection']} | "
          f"AC1 call @ {_s2t(info['ac1_call_time'])} | "
          f"AC2 call @ {_s2t(info['ac2_call_time'])}")
    return info


# ── Feature extraction ────────────────────────────────────────────────────────

_FEATURES = ['lat', 'lon', 'heading', 'alt', 'ground_speed']
_N_STEPS  = 480
_N_FEAT   = len(_FEATURES)
TRAJ_DIM  = _N_STEPS * _N_FEAT

def extract_features(df: pd.DataFrame, acid: str):
    sub = (df[df['acid'] == acid]
           .sort_values('sim_time')
           .reset_index(drop=True))
    if sub.empty:
        raise ValueError(f"No rows found for aircraft '{acid}' in CSV.")
    data = sub[_FEATURES].values.astype(np.float32)
    if len(data) > _N_STEPS:
        data = data[:_N_STEPS]
    elif len(data) < _N_STEPS:
        pad  = np.tile(data[-1], (_N_STEPS - len(data), 1))
        data = np.vstack([data, pad])
    stats = {'min': data.min(axis=0), 'max': data.max(axis=0)}
    norm  = (data - stats['min']) / (stats['max'] - stats['min'] + 1e-8) * 2 - 1
    return norm.astype(np.float32), stats, data

def denorm(arr: np.ndarray, stats: dict) -> np.ndarray:
    return (arr + 1) / 2 * (stats['max'] - stats['min'] + 1e-8) + stats['min']


# ── GAN ───────────────────────────────────────────────────────────────────────

LATENT_DIM = 64

def build_generator(latent_dim=LATENT_DIM, output_dim=TRAJ_DIM):
    z = keras.Input(shape=(latent_dim,), name='noise')
    x = layers.Dense(256, use_bias=False)(z)
    x = layers.BatchNormalization(momentum=0.9)(x)
    x = layers.LeakyReLU(0.2)(x)
    x = layers.Dense(512, use_bias=False)(x)
    x = layers.BatchNormalization(momentum=0.9)(x)
    x = layers.LeakyReLU(0.2)(x)
    x = layers.Dense(256, use_bias=False)(x)
    x = layers.BatchNormalization(momentum=0.9)(x)
    x = layers.LeakyReLU(0.2)(x)
    out = layers.Dense(output_dim, activation='tanh', name='trajectory')(x)
    return Model(inputs=z, outputs=out, name='Generator')

def build_discriminator(input_dim=TRAJ_DIM):
    traj = keras.Input(shape=(input_dim,), name='trajectory')
    x = layers.Dense(256)(traj)
    x = layers.LeakyReLU(0.2)(x)
    x = layers.Dropout(0.3)(x)
    x = layers.Dense(128)(x)
    x = layers.LeakyReLU(0.2)(x)
    x = layers.Dropout(0.3)(x)
    x = layers.Dense(64)(x)
    x = layers.LeakyReLU(0.2)(x)
    out = layers.Dense(1, activation='sigmoid', name='real_prob')(x)
    return Model(inputs=traj, outputs=out, name='Discriminator')

class TrajectoryGAN:
    def __init__(self, latent_dim=LATENT_DIM, traj_dim=TRAJ_DIM,
                 lr_g=2e-4, lr_d=2e-4, seed=42):
        tf.random.set_seed(seed);  np.random.seed(seed)
        self.latent_dim = latent_dim;  self.traj_dim = traj_dim
        self.G = build_generator(latent_dim, traj_dim)
        self.D = build_discriminator(traj_dim)
        self.opt_g = optimizers.Adam(learning_rate=lr_g, beta_1=0.5)
        self.opt_d = optimizers.Adam(learning_rate=lr_d, beta_1=0.5)
        self.bce   = losses.BinaryCrossentropy()

    def _noise(self, n):
        return tf.random.normal((n, self.latent_dim))

    def _augment(self, real_flat, n=8, sigma=0.02):
        tiled = np.tile(real_flat, (n, 1)).astype(np.float32)
        noisy = tiled + np.random.normal(0, sigma, tiled.shape).astype(np.float32)
        return tf.constant(np.clip(noisy, -1.0, 1.0))

    @tf.function
    def _train_d(self, real_batch, fake_batch):
        ones  = tf.ones ((tf.shape(real_batch)[0], 1))
        zeros = tf.zeros((tf.shape(fake_batch)[0], 1))
        with tf.GradientTape() as tape:
            loss = (self.bce(ones,  self.D(real_batch, training=True)) +
                    self.bce(zeros, self.D(fake_batch, training=True)))
        grads = tape.gradient(loss, self.D.trainable_variables)
        self.opt_d.apply_gradients(zip(grads, self.D.trainable_variables))
        return loss

    @tf.function
    def _train_g(self, batch_size):
        z    = self._noise(batch_size)
        ones = tf.ones((batch_size, 1))
        with tf.GradientTape() as tape:
            fake = self.G(z, training=True)
            loss = self.bce(ones, self.D(fake, training=False))
        grads = tape.gradient(loss, self.G.trainable_variables)
        self.opt_g.apply_gradients(zip(grads, self.G.trainable_variables))
        return loss

    def train(self, traj1_norm, traj2_norm, epochs=500, batch_size=8, verbose=True):
        flat1 = traj1_norm.flatten().reshape(1, -1)
        flat2 = traj2_norm.flatten().reshape(1, -1)
        d_hist, g_hist = [], []
        for epoch in range(1, epochs + 1):
            for flat in (flat1, flat2):
                real_batch = self._augment(flat, n=batch_size)
                fake_batch = self.G(self._noise(batch_size), training=False)
                d_loss = self._train_d(real_batch, fake_batch)
                g_loss = self._train_g(batch_size)
            d_hist.append(float(d_loss));  g_hist.append(float(g_loss))
            if verbose and epoch % 100 == 0:
                print(f"  Epoch {epoch:5d}/{epochs} | "
                      f"D_loss={d_loss:.4f} | G_loss={g_loss:.4f}")
        return d_hist, g_hist

    def save(self, path):
        self.G.save_weights(os.path.join(path, 'generator.weights.h5'))
        self.D.save_weights(os.path.join(path, 'discriminator.weights.h5'))
        print(f"  [GAN] Weights saved -> {path}")

    def load(self, path):
        self.G.load_weights(os.path.join(path, 'generator.weights.h5'))
        self.D.load_weights(os.path.join(path, 'discriminator.weights.h5'))
        print(f"  [GAN] Weights loaded <- {path}")


# ── Waypoint updater ──────────────────────────────────────────────────────────

def update_waypoints(orig_wpts: list,
                     lat_shift: float,
                     lon_shift: float) -> list:
    """
    Apply a constant uniform lat/lon offset to every waypoint (rigid body
    shift).  Alt and spd are carried over unchanged from the original SCN.
    """
    new_wpts = []
    for wpt in orig_wpts:
        w = dict(wpt)
        w['lat'] = wpt['lat'] + lat_shift
        w['lon'] = wpt['lon'] + lon_shift
        new_wpts.append(w)
    return new_wpts


# ── SCN output builders ───────────────────────────────────────────────────────

def build_scn(cre_info, waypoints, del_acid, filename):
    acid  = cre_info['acid']
    first = waypoints[0]
    lines = [
        f'#{filename}\n',
        '00:00:00.00>TRAIL ON\n',
        '00:00:00.00>PLUGIN TRACKLOG\n',
        '\n',
        f"00:00:00.00>  CRE  {acid}     {cre_info['actype']}     "
        f"{first['lat']:.4f}   {first['lon']:.4f} "
        f"{cre_info['hdg']:.1f}       "
        f"{first['alt']:.1f} \t{first['spd']:.1f}\n",
    ]
    for i, wpt in enumerate(waypoints):
        t   = _s2t(i + 1)
        tag = f"{acid}{wpt['wpt_idx']:03d}"
        lines += [
            f"{t}> ADDWPT {acid}   {wpt['lat']:.4f}   \t{wpt['lon']:.4f}\n",
            f"{t}> {acid}  AT {tag} DO ALT {acid}  \t{wpt['alt']:.1f}\n",
            f"{t}> {acid}  AT {tag} DO SPD {acid}  \t{wpt['spd']:.1f}\n",
        ]
    if del_acid:
        t_del = _s2t(len(waypoints) + 1)
        tag   = f"{acid}{len(waypoints):03d}"
        lines.append(f"{t_del}> {acid}  AT {tag} DO DEL    \t{del_acid} \n")
    return lines

def build_conflict_scn(ac1_scn, ac2_scn, t1_call, t2_call,
                        inter_lat, inter_lon, quit_t, filename):
    return [
        '00:00:00.00>TRAIL ON\n',
        '00:00:00.00>DT 10\n',
        '00:00:00.00>PLUGIN RIFLOG_THUNDER\n',
        '00:00:00.00>ASAS ON\n',
        '\n',
        f'# Intersection lat={inter_lat:.6f}, lon={inter_lon:.6f}, alt=N/A\n',
        f'{_s2t(t1_call)}> CALL {ac1_scn}\n',
        f'{_s2t(t2_call)}> CALL {ac2_scn}\n',
    ]


# ── Folder discovery helpers ──────────────────────────────────────────────────

def find_scn_for_acid(scn_folder: str, acid: str) -> str:
    pattern = os.path.join(scn_folder, f'*{acid}*.scn')
    matches = glob.glob(pattern)
    if not matches:
        raise FileNotFoundError(
            f"No SCN file found for acid='{acid}' in '{scn_folder}'\n"
            f"  (searched: {pattern})")
    return matches[0]

def find_preconflict_csv(preconflict_folder: str, acid1: str, acid2: str) -> str:
    for csv_path in glob.glob(os.path.join(preconflict_folder, '*.csv')):
        name = os.path.basename(csv_path)
        if acid1 in name and acid2 in name:
            return csv_path
    # Fallback: check acid values inside each CSV
    for csv_path in glob.glob(os.path.join(preconflict_folder, '*.csv')):
        try:
            df = pd.read_csv(csv_path, nrows=200)
            if 'acid' in df.columns:
                acids_in_file = set(df['acid'].unique())
                if acid1 in acids_in_file and acid2 in acids_in_file:
                    return csv_path
        except Exception:
            continue
    raise FileNotFoundError(
        f"No preconflict CSV found for acids '{acid1}' and '{acid2}' "
        f"in '{preconflict_folder}'")


print("=" * 60)
print("  Cell 0 complete — all functions loaded ✓")
print("  Next: run Cell 1 to configure paths")
print("=" * 60)

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  CELL 1 — Configuration                                                ║
# ║  Set the three input folders and output folder, then run Cell 2        ║
# ╚══════════════════════════════════════════════════════════════════════════╝

# ── Mount Google Drive (if using Drive) ───────────────────────────────────────
from google.colab import drive
drive.mount('/content/drive')

# ── Input folders ─────────────────────────────────────────────────────────────
SCN_FOLDER         = '/content/drive/MyDrive/GAN/2D_trajectory'             # individual aircraft SCN folder
PRECONFLICT_FOLDER = '/content/drive/MyDrive/GAN/preconflict_data4'          # preconflict CSV folder
CONFLICT_FOLDER    = '/content/drive/MyDrive/GAN/conflict_data4'             # conflict SCN folder

# ── Output folder ─────────────────────────────────────────────────────────────
OUTPUT_DIR = 'gan_output'   # one sub-folder will be created per conflict

# ── GAN parameters ────────────────────────────────────────────────────────────
SEED       = 42
GAN_EPOCHS = 500
GAN_BATCH  = 8

# ── Displacement range ────────────────────────────────────────────────────────
MIN_SHIFT_NM = 0.0   # minimum rigid shift (NM)
MAX_SHIFT_NM = 4.5   # maximum rigid shift (NM)

print("=" * 60)
print("  Configuration:")
print(f"    SCN folder         : {SCN_FOLDER}")
print(f"    Preconflict folder : {PRECONFLICT_FOLDER}")
print(f"    Conflict folder    : {CONFLICT_FOLDER}")
print(f"    Output folder      : {OUTPUT_DIR}")
print(f"    Shift range        : {MIN_SHIFT_NM} - {MAX_SHIFT_NM} NM")
print(f"    GAN epochs         : {GAN_EPOCHS}")
print("  Run Cell 2 to process all conflicts")
print("=" * 60)

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  CELL 2 — GAN Pipeline + Batch Runner                                  ║
# ║  Trains GAN on each conflict pair, then outputs rigid-shifted SCNs     ║
# ╚══════════════════════════════════════════════════════════════════════════╝

def run_gan_pipeline(csv_path, scn_ac1_path, scn_ac2_path, conflict_path,
                     output_dir, seed=42, epochs=500, batch_size=8,
                     min_shift_nm=0.0, max_shift_nm=4.5):

    os.makedirs(output_dir, exist_ok=True)

    # ── STEP 1: Load ──────────────────────────────────────────────────────────
    print('\n' + '='*65)
    print(' STEP 1: Loading input data')
    print('='*65)
    df            = load_csv(csv_path)
    scn1          = parse_scn(scn_ac1_path)
    scn2          = parse_scn(scn_ac2_path)
    conflict_info = parse_conflict_scn(conflict_path)
    acid1 = scn1['cre']['acid'];  acid2 = scn2['cre']['acid']
    print(f'  Aircraft 1 : {acid1}  |  Aircraft 2 : {acid2}')
    print(f'  Original CALL times from conflict .scn:')
    print(f'    {acid1} : {_s2t(conflict_info["ac1_call_time"] or 0.0)}')
    print(f'    {acid2} : {_s2t(conflict_info["ac2_call_time"] or 0.0)}')

    # ── STEP 2: Extract features & train GAN ─────────────────────────────────
    print('\n' + '='*65)
    print(f' STEP 2: Extracting features and training GAN ({epochs} epochs)')
    print('='*65)
    norm1, stats1, raw1 = extract_features(df, acid1)
    norm2, stats2, raw2 = extract_features(df, acid2)
    gan = TrajectoryGAN(seed=seed)
    gan.train(norm1, norm2, epochs=epochs, batch_size=batch_size)
    print(f'  GAN training complete ✓')

    # ── STEP 3: Read original intersection from conflict SCN ──────────────────
    print('\n' + '='*65)
    print(' STEP 3: Reading original intersection from conflict SCN')
    print('='*65)
    orig_lat = conflict_info['intersection'][0]
    orig_lon = conflict_info['intersection'][1]
    print(f'  Original intersection : lat={orig_lat:.6f}, lon={orig_lon:.6f}')
    print(f'  (Rigid shift will move both trajectories uniformly — '
          f'intersection moves by the same offset)')

    # ── STEP 4: Compute constant rigid shift for both aircraft ────────────────
    print('\n' + '='*65)
    print(f' STEP 4: Computing rigid shift [{min_shift_nm}, {max_shift_nm}] NM')
    print('='*65)

    rng     = np.random.default_rng(seed)
    bearing = rng.uniform(0, 2 * math.pi)               # random direction
    dist_nm = rng.uniform(min_shift_nm, max_shift_nm)   # 0-4.5 NM shift

    # 1 NM ≈ 1/60 degree latitude; longitude degree shrinks with cos(lat)
    ref_lat = scn1['waypoints'][len(scn1['waypoints'])//2]['lat']
    lat_off =  dist_nm * math.cos(bearing) / 60.0
    lon_off =  dist_nm * math.sin(bearing) / (60.0 * math.cos(math.radians(ref_lat)))

    print(f'  Bearing        : {math.degrees(bearing):.1f}°')
    print(f'  Shift distance : {dist_nm:.3f} NM')
    print(f'  delta_lat      : {lat_off:+.6f}°')
    print(f'  delta_lon      : {lon_off:+.6f}°')
    print(f'  (same constant offset applied to EVERY waypoint of both aircraft)')

    wpts1 = update_waypoints(scn1['waypoints'], lat_off, lon_off)
    wpts2 = update_waypoints(scn2['waypoints'], lat_off, lon_off)

    # ── STEP 5: Find new intersection point ───────────────────────────────────
    print('\n' + '='*65)
    print(' STEP 5: Finding new intersection point')
    print('='*65)
    i1, i2, dist_nm_approach = find_closest_approach(
        wpts1[:min(_N_STEPS, len(wpts1))],
        wpts2[:min(_N_STEPS, len(wpts2))])
    inter_lat = (wpts1[i1]['lat'] + wpts2[i2]['lat']) / 2
    inter_lon = (wpts1[i1]['lon'] + wpts2[i2]['lon']) / 2
    print(f'  Confirmed intersection : lat={inter_lat:.6f}, lon={inter_lon:.6f}')
    print(f'  Closest approach       : {dist_nm_approach:.3f} NM')

    # ── STEP 6: CALL times — unchanged from original conflict SCN ─────────────
    print('\n' + '='*65)
    print(' STEP 6: CALL times (rigid shift — original timing preserved)')
    print('='*65)
    t1_call = conflict_info['ac1_call_time'] or 0.0
    t2_call = conflict_info['ac2_call_time'] or 0.0
    print(f'  {acid1} CALL @ {_s2t(t1_call)}  (unchanged)')
    print(f'  {acid2} CALL @ {_s2t(t2_call)}  (unchanged)')

    # ── STEP 7: Write output files ────────────────────────────────────────────
    print('\n' + '='*65)
    print(' STEP 7: Writing output files')
    print('='*65)
    ts = datetime.now().strftime('%Y%m%d_%H%M%S')
    n1 = f'GAN_{acid1}_{ts}.scn'
    n2 = f'GAN_{acid2}_{ts}.scn'
    nc = f'GAN_Conflict_{acid1}_{acid2}_{ts}.scn'

    def _write(name, lines):
        p = os.path.join(output_dir, name)
        with open(p, 'w') as fh: fh.writelines(lines)
        print(f'  OK  {name}  ({len(lines)} lines)')
        return p

    p1 = _write(n1, build_scn(scn1['cre'], wpts1, scn1['del_acid'], n1))
    p2 = _write(n2, build_scn(scn2['cre'], wpts2, scn2['del_acid'], n2))
    quit_t = max(t1_call, t2_call) + max(len(wpts1), len(wpts2)) + 60
    pc = _write(nc, build_conflict_scn(n1, n2, t1_call, t2_call,
                                        inter_lat, inter_lon, quit_t, nc))

    # ── Summary ───────────────────────────────────────────────────────────────
    print('\n' + '='*65)
    print(' GENERATION SUMMARY')
    print('='*65)
    print(f'  Original  intersection : lat={orig_lat:.6f}, lon={orig_lon:.6f}')
    print(f'  New       intersection : lat={inter_lat:.6f}, lon={inter_lon:.6f}')
    print(f'  Rigid shift            : {dist_nm:.3f} NM  bearing={math.degrees(bearing):.1f}°')
    print(f'  delta_lat={lat_off:+.6f}°  delta_lon={lon_off:+.6f}°')
    print(f'  Closest approach       : {dist_nm_approach:.3f} NM  '
          f'({"Conflict <5 NM ✓" if dist_nm_approach < 5 else "No lateral conflict ✗"})')
    print(f'  {acid1} CALL @ {_s2t(t1_call)}')
    print(f'  {acid2} CALL @ {_s2t(t2_call)}')
    print(f'\n  Output -> {output_dir}/')
    for f in (n1, n2, nc): print(f'    {f}')
    print('='*65)

    return dict(scn_ac1=p1, scn_ac2=p2, conflict_scn=pc,
                intersection=(inter_lat, inter_lon),
                shift_nm=dist_nm, bearing_deg=math.degrees(bearing),
                closest_approach_nm=dist_nm_approach,
                t1_call=t1_call, t2_call=t2_call)


# ── Batch runner ──────────────────────────────────────────────────────────────

def run_batch(scn_folder, preconflict_folder, conflict_folder,
              output_dir, seed=42, epochs=500, batch_size=8,
              min_shift_nm=0.0, max_shift_nm=4.5):

    # ── Clear old output ──────────────────────────────────────────────────────
    if os.path.exists(output_dir):
        shutil.rmtree(output_dir)
        print(f'  Cleared old output -> {output_dir}/')
    os.makedirs(output_dir, exist_ok=True)

    conflict_scns = sorted(glob.glob(os.path.join(conflict_folder, '*.scn')))
    if not conflict_scns:
        raise FileNotFoundError(f"No .scn files found in '{conflict_folder}'")

    print('\n' + '#'*65)
    print(f'  Batch GAN — found {len(conflict_scns)} conflict(s) to process')
    print('#'*65)

    results = []

    for conflict_idx, conflict_path in enumerate(conflict_scns, 1):
        conflict_name = os.path.splitext(os.path.basename(conflict_path))[0]
        print('\n' + '█'*65)
        print(f'  CONFLICT {conflict_idx}/{len(conflict_scns)}: {conflict_name}')
        print('█'*65)

        try:
            # ── Parse conflict SCN to identify the two aircraft ────────────────
            conflict_info = parse_conflict_scn(conflict_path)

            def acid_from_scn_ref(scn_ref):
                """Extract ACID from a CALL-referenced filename."""
                stem = os.path.splitext(os.path.basename(scn_ref))[0]
                parts = stem.replace('Corrected__', '').replace('Corrected_', '')
                return parts.split('_')[0]

            acid1 = acid_from_scn_ref(conflict_info.get('ac1_scn', ''))
            acid2 = acid_from_scn_ref(conflict_info.get('ac2_scn', ''))
            print(f'  Identified ACIDs: {acid1}, {acid2}')

            # ── Locate individual aircraft .scn files ──────────────────────────
            scn_ac1_path = find_scn_for_acid(scn_folder, acid1)
            scn_ac2_path = find_scn_for_acid(scn_folder, acid2)
            print(f'  AC1 SCN : {os.path.basename(scn_ac1_path)}')
            print(f'  AC2 SCN : {os.path.basename(scn_ac2_path)}')

            # ── Locate preconflict CSV ─────────────────────────────────────────
            csv_path = find_preconflict_csv(preconflict_folder, acid1, acid2)
            print(f'  CSV     : {os.path.basename(csv_path)}')

            # ── Create per-conflict output folder ──────────────────────────────
            conflict_output_dir = os.path.join(output_dir, conflict_name)
            os.makedirs(conflict_output_dir, exist_ok=True)

            # ── Run GAN pipeline ───────────────────────────────────────────────
            result = run_gan_pipeline(
                csv_path        = csv_path,
                scn_ac1_path    = scn_ac1_path,
                scn_ac2_path    = scn_ac2_path,
                conflict_path   = conflict_path,
                output_dir      = conflict_output_dir,
                seed            = seed,
                epochs          = epochs,
                batch_size      = batch_size,
                min_shift_nm    = min_shift_nm,
                max_shift_nm    = max_shift_nm,
            )
            result['conflict_name'] = conflict_name
            result['status']        = 'OK'
            results.append(result)

        except Exception as exc:
            import traceback
            print(f'  [ERROR] Conflict "{conflict_name}" failed: {exc}')
            traceback.print_exc()
            results.append(dict(conflict_name=conflict_name,
                                status='ERROR', error=str(exc)))

    # ── Final summary ─────────────────────────────────────────────────────────
    print('\n' + '#'*65)
    print('  BATCH COMPLETE')
    print('#'*65)
    ok  = [r for r in results if r.get('status') == 'OK']
    err = [r for r in results if r.get('status') == 'ERROR']
    print(f'  Processed : {len(results)} conflict(s)')
    print(f'  Success   : {len(ok)}')
    print(f'  Errors    : {len(err)}')
    if err:
        print('  Failed conflicts:')
        for r in err:
            print(f'    - {r["conflict_name"]}: {r["error"]}')
    print(f'\n  Output root -> {output_dir}/')
    for r in ok:
        print(f'    {r["conflict_name"]}/')
    print('#'*65)
    return results


# ── Run ───────────────────────────────────────────────────────────────────────
batch_results = run_batch(
    scn_folder         = SCN_FOLDER,
    preconflict_folder = PRECONFLICT_FOLDER,
    conflict_folder    = CONFLICT_FOLDER,
    output_dir         = OUTPUT_DIR,
    seed               = SEED,
    epochs             = GAN_EPOCHS,
    batch_size         = GAN_BATCH,
    min_shift_nm       = MIN_SHIFT_NM,
    max_shift_nm       = MAX_SHIFT_NM,
)

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  CELL 3 — Download outputs                                             ║
# ║  Zips the entire gan_output/ folder and downloads it                   ║
# ╚══════════════════════════════════════════════════════════════════════════╝

from google.colab import files
shutil.make_archive('gan_output', 'zip', OUTPUT_DIR)
files.download('gan_output.zip')
print('Download started ✓')